Mayhem Heroes mayhem integration
mayhemheroes/nuspell pull request #1
Opened 2022-05-17 00:06 UTC by bmwtsn098

2022-07-23 23:07 UTC, xansec requested changes
Please make the requested changes.

2022-07-23 23:07 UTC, xansec commented on Dockerfile
> +# Build Stage:
Please include a package stage to reduce image size.

2022-07-23 23:07 UTC, xansec commented on Mayhemfile
> +# Namespaced project name that the target belongs to
Project name should be generic, and you may omit the image name as it is interpolated during the action run. Same with duration.

2022-07-24 06:25 UTC, bmwtsn098 commented
I've added the requested changes. Let me know if everything looks good. Thanks

2022-07-25 20:19 UTC, xansec commented
Approved!

2022-07-25 20:19 UTC, merged